### ISSUE TITLE
插值

### ISSUE THREAD

**Issue by NewRudy** [SharedMemory-F/Interpolation#1]
老哥你怎写的这些插值算法哇，后期你会去写一下拟合或者逼近的算法吗

**Comment by iiiifan** [comment]
我是在学习数值分析课程的时候看着老师的ppt上原理对应实现了一下，我不是数学专业的，后面应该不会更新这部分内容了。




| |
张壹帆
|
|
邮箱：ffan_zhang@126.com
|

签名由 网易邮箱大师 定制

在2020年09月23日 21:30，WUTIAN 写道：

老哥你怎写的这些插值算法哇，后期你会去写一下拟合或者逼近的算法吗

**Comment by NewRudy** [comment]
喔喔，好的，我在看原理和你的代码，卡在三次样条插值法了，谢谢老哥的代码了




吴天
wutinxin@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SharedMemory-F/Interpolation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月23日(星期三) 晚上9:58
收件人:&nbsp;"SharedMemory-F/Interpolation"<Interpolation@noreply.github.com&gt;;
抄送:&nbsp;"兮卌"<1344591831@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SharedMemory-F/Interpolation] 插值 (#1)





 我是在学习数值分析课程的时候看着老师的ppt上原理对应实现了一下，我不是数学专业的，后面应该不会更新这部分内容了。
 
 
 
 
 | |
 张壹帆
 |
 |
 邮箱：ffan_zhang@126.com
 |
 
 签名由 网易邮箱大师 定制
 
 在2020年09月23日 21:30，WUTIAN 写道：
 
 老哥你怎写的这些插值算法哇，后期你会去写一下拟合或者逼近的算法吗
